### ISSUE TITLE
can't see rgba 

### ISSUE THREAD

**Issue by danjm75** [flovan/interstellar-package#1]
Great colors , I really like all of them. Then I realized the colors I had in rgba were barely visible.

**Comment by flovan** [comment]
With "the colors I had in rgba", do you mean the colors rendered by a color preview package in your code editor?

A screenshot would be helpful here.

-F

**Comment by danjm75** [comment]
Wow man I feel like an ass. I just went through and checked all of your
options and they all look great. In fact I am excited to use mercury
especially. Last night or this morning after 12 hours of coding I must have
been seeing through different eyes! I'm going to pull a "take back" on this
one. Sorry for the waste of your time and thank you for taking the time to
respond to my unwarranted complaints. Happy coding MoFo's ;)

**Comment by flovan** [comment]
No problem at all; I've been there myself ;)
Enjoy your space explorations and let me know if you stumble onto any issues.
